# Generated by Django 3.2.6 on 2021-09-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_usuario', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('paterno_usuario', models.CharField(max_length=45)),
                ('materno_usuario', models.CharField(max_length=45)),
                ('rol_usuario', models.CharField(max_length=20)),
                ('correo_usuario', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('contrasena_usuario', models.CharField(max_length=90)),
            ],
        ),
    ]
