# Generated by Django 3.2.6 on 2021-09-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWWW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='materno_usuario',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
