# Generated by Django 3.2.6 on 2021-10-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWWW', '0002_alter_usuarios_materno_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('ID_proveedor', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=45)),
                ('direccion_proveedor', models.CharField(max_length=20)),
                ('celular_proveedor', models.CharField(max_length=45)),
                ('encargado_proveedor', models.CharField(max_length=45)),
                ('correo_proveedor', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
    ]
