# Generated by Django 3.2.6 on 2021-10-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWWW', '0003_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('ID_item', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item', models.CharField(max_length=45)),
                ('cantidad_item', models.IntegerField(max_length=20)),
                ('referencia_item', models.CharField(max_length=45)),
                ('estado_item', models.CharField(max_length=45)),
                ('proveedor_ID_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Provee_inventario', to='ProyectoWWW.proveedores')),
            ],
        ),
    ]
