# Generated by Django 3.2.6 on 2021-10-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWWW', '0004_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_item',
            field=models.IntegerField(),
        ),
    ]
