# Generated by Django 3.2.6 on 2022-07-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWWW', '0005_alter_inventario_cantidad_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='proveedor_ID_item',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
