# Generated by Django 3.2.6 on 2022-07-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas_almacen',
            fields=[
                ('id_ventas_a', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zapatillas_a', models.IntegerField()),
                ('id_zapatillas_n', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('fecha_venta', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas_linea',
            fields=[
                ('id_ventas_l', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zapatillas_a', models.IntegerField()),
                ('id_zapatillas_n', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('fecha_venta', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zapatillas_a_almacen',
            fields=[
                ('id_zap_a_almacen', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=50)),
                ('precio_compra', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
                ('talla_43', models.IntegerField()),
                ('talla_42', models.IntegerField()),
                ('talla_41', models.IntegerField()),
                ('talla_40', models.IntegerField()),
                ('talla_39', models.IntegerField()),
                ('talla_38', models.IntegerField()),
                ('talla_37', models.IntegerField()),
                ('talla_36', models.IntegerField()),
                ('talla_35', models.IntegerField()),
                ('talla_34', models.IntegerField()),
                ('talla_33', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zapatillas_a_linea',
            fields=[
                ('id_zap_a_linea', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=50)),
                ('precio_compra', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
                ('talla_43', models.IntegerField()),
                ('talla_42', models.IntegerField()),
                ('talla_41', models.IntegerField()),
                ('talla_40', models.IntegerField()),
                ('talla_39', models.IntegerField()),
                ('talla_38', models.IntegerField()),
                ('talla_37', models.IntegerField()),
                ('talla_36', models.IntegerField()),
                ('talla_35', models.IntegerField()),
                ('talla_34', models.IntegerField()),
                ('talla_33', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zapatillas_n_almacen',
            fields=[
                ('id_zap_n_almacen', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=50)),
                ('precio_compra', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
                ('talla_32', models.IntegerField()),
                ('talla_31', models.IntegerField()),
                ('talla_30', models.IntegerField()),
                ('talla_29', models.IntegerField()),
                ('talla_28', models.IntegerField()),
                ('talla_27', models.IntegerField()),
                ('talla_26', models.IntegerField()),
                ('talla_25', models.IntegerField()),
                ('talla_24', models.IntegerField()),
                ('talla_23', models.IntegerField()),
                ('talla_22', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zapatillas_n_linea',
            fields=[
                ('id_zap_n_linea', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=50)),
                ('precio_compra', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
                ('talla_32', models.IntegerField()),
                ('talla_31', models.IntegerField()),
                ('talla_30', models.IntegerField()),
                ('talla_29', models.IntegerField()),
                ('talla_28', models.IntegerField()),
                ('talla_27', models.IntegerField()),
                ('talla_26', models.IntegerField()),
                ('talla_25', models.IntegerField()),
                ('talla_24', models.IntegerField()),
                ('talla_23', models.IntegerField()),
                ('talla_22', models.IntegerField()),
            ],
        ),
    ]
