# Generated by Django 3.2.6 on 2022-08-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASA', '0002_ventas_almacen_ventas_linea_zapatillas_a_almacen_zapatillas_a_linea_zapatillas_n_almacen_zapatillas_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas_almacen',
            name='id_zapatillas_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ventas_almacen',
            name='id_zapatillas_n',
            field=models.IntegerField(null=True),
        ),
    ]
