# Generated by Django 3.2.6 on 2022-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASA', '0003_auto_20220805_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
    ]
