# Generated by Django 3.2.6 on 2022-08-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASA', '0005_gastos_variable_almacen_gastos_variable_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas_almacen',
            name='fecha_venta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ventas_linea',
            name='fecha_venta',
            field=models.DateField(),
        ),
    ]
