# Generated by Django 3.2.6 on 2022-08-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASA', '0006_auto_20220807_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos_Fijos_Almacen',
            fields=[
                ('id_gasto_variable_l', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
